server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice_commandes?useSSL=false&serverTimezone=UTC
    username: root
    password: Raja2013@@@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

mes-config-ms:
  commandes-last: 10  # Propriété personnalisée pour le nombre de commandes à afficher

microservice:
  commandes:
    jwtSecret: MySuperSecretKeyForJWT
    jwtExpirationMs: 86400000

logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    org.hibernate: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info  # Exposer les endpoints nécessaires
  endpoint:
    health:
      show-details: always
